#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

blank_issues_enabled: false
# contact_links:
# - name: ğŸ“š Docs
#   url: https://github.com/sammcj/${{ github.repository }}#-usage
#   about: Checkout ${{ github.repository }}'s documentation.
# - name: ğŸš€ Feature Request
#   url: https://github.com/sammcj/${{ github.repository }}/discussions/new?category=ideas
#   about: Share ideas for new features
# - name: â“ Ask a Question
#   url: https://github.com/sammcj/${{ github.repository }}/discussions/new?category=q-a
#   about: Ask the community for help
